### ISSUE TITLE
formalize active annotations testing

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#101]
We should use [XtendCompilerTester](https://eclipse.org/xtend/documentation/204_activeannotations.html#active-annotation-classpath) for all future annotations, and start with a TDD approach.

**Comment by tobykurien** [comment]
It seems rather tedious, compared to implementing a test case in the XtendroidTestCase app. The latter:

- is not whitespace-sensitive
- picks up regressions
- does not need to be updated everytime the annotation is updated (except to test for new features)
- acts as documentation and a sample for the annotations
- does a real-world test in the environment the production code runs in, and so can pick up null pointer exceptions, etc.

That's why I would personally rather stick to the way we have been testing up to now.

**Comment by Buggaboo** [comment]
Hm, good points. I tried doing it that way, but it doesn't increase my coding productivity. I did it in a TDD way though , i.e. `./gradlew :XtendroidTest:cAT`

**Comment by tobykurien** [comment]
You're more than welcome to continue the TDD approach :)
