### ISSUE TITLE
Kotlin

### ISSUE THREAD

**Issue by Buggaboo** [tobykurien/Xtendroid#76]
Seen this?

https://github.com/JetBrains/anko

Someone is trying the same thing :) No active annotations tho.

**Comment by tobykurien** [comment]
Yes, it was mentioned a while ago on Hacker News, and is now getting regular attention on the Android Weekly newsletter. Looks interesting, but like you say, it missed Active Annotations, meaning it does far less than what Xtend/Xtendroid provides. I am not convinced of their DSL for UI, although it does look promising. @svenefftinge made something similar using just a simple UI Builder class (https://github.com/tobykurien/Xtendroid/blob/master/examples/HelloWorld/src/com/example/helloworld/HelloWorldActivity.xtend#L51-L58) about a year ago!

I tried submitting Xtendroid several times to Android Weekly (also Reddit/Hacker news) long before Eclipse was phased out - they all flat out ignored it, however they are all featuring Kotlin and associated libraries with increasing frequency. I guess there's a bias towards JetBrains technologies and a bias against Eclipse.

**Comment by svenefftinge** [comment]
The Kotlin & Android story got a big boost when Jake Wharton, wrote this document:
https://plus.google.com/+JakeWharton/posts/WSCoqkJ5MBj

I think there is nothing else than spreading the word that we can do ... and of course releasing the IDEA plugin. It is hilarious how much they hacked the compiler and tools in order to achieve something similar to what you guys just did with API in Xtendroid. And still it is not even close :-)
I refer to this : http://kotlinlang.org/docs/tutorials/android-plugin.html

We really need more people talking about Xtend!

**Comment by tobykurien** [comment]
Jake Wharton did comment on my Xtendroid post to reddit, but he wasn't interested or impressed: https://www.reddit.com/r/androiddev/comments/2ncpfb/xtendroid_android_library_for_productive_android/

**Comment by Buggaboo** [comment]
First they ignore you, then they laugh at you...

**Comment by svenefftinge** [comment]
who is laughing?

**Comment by Buggaboo** [comment]
Noone, but if Gandhi is to be believed...

**Comment by PerfectCarl** [comment]
I'm not ignoring nor laughing. 
Just thanking you for your work.

I love xtend.
Well done, guys.
